---
- name: Upgrade all packages
  become: yes
  yum:
    name: '*'
    state: latest
- name: Ensure basic packages
  become: yes
  package:
    name: '{{item}}'
    state: latest
  loop:
      - git
      - htop
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
      - p7zip
      - unzip
      - wget
      - gnome-tweaks
      - terminator
      - transmission
      - libreoffice-base
      - gparted
      - icedtea-web
      - npm
      - libreoffice-draw.x86_64
      - whois
      - syslinux
# fpassword
      - xclip
# VirtualBox
      - gcc
      - make
      - perl
      - kernel-devel
      - elfutils-libelf-devel
# Prompt fonts
      - powerline-fonts
- name: Add Extra Repositories
  become: yes
  yum_repository:
    name: '{{item.name}}'
    description: '{{item.description}}'
    baseurl: '{{item.baseurl}}'
    enabled:  yes
    gpgcheck: yes
    gpgkey: '{{item.gpgkey}}'
  loop:
    - name: sublime-text
      description: sublime-text-stable
      baseurl: https://download.sublimetext.com/rpm/stable/x86_64
      gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    - name: google-chrome-stable
      description: Google Chrome Stable x86_64 - stable
      baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
      gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    - name: KeeWeb
      description: KeeWeb x86_64
      baseurl: https://download.copr.fedorainfracloud.org/results/jclay/KeeWeb/epel-8-x86_64
      gpgkey: https://download.copr.fedorainfracloud.org/results/jclay/KeeWeb/pubkey.gpg
    - name: AnyDesk
      description: AnyDesk x86_64
      baseurl: http://rpm.anydesk.com/rhel/8/x86_64
      gpgkey: https://keys.anydesk.com/repos/RPM-GPG-KEY
    - name: Skype
      description: Skype - stable
      baseurl: https://repo.skype.com/rpm/stable/
      gpgkey: https://repo.skype.com/data/SKYPE-GPG-KEY
    - name: Hashicorp-Stable
      description: Hashicorp Stable - x86_64
      baseurl: https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable
      gpgkey: https://rpm.releases.hashicorp.com/gpg
- name: Add Extra packages
  become: yes
  package:
    name: '{{item}}'
    state: present
  loop:
    - sublime-text
    - google-chrome-stable
    - KeeWeb
    - anydesk
    - skypeforlinux
    - vagrant
- name: Get Jetbrains Toolbox Installer
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh
    dest: /tmp/jetbrains-toolbox.sh
- name: Install Jenbrains Toolbox
  become: yes
  ansible.builtin.shell: 'sh /tmp/jetbrains-toolbox.sh'
  args:
    creates: /usr/local/bin/jetbrains-toolbox
- name: Add flathub flatpak repository remote
  become: no
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
- name: Install Flathub apps
  become: no
  community.general.flatpak:
    name: '{{item}}'
    state: present
    method: user
  loop:
   - org.videolan.VLC
   - com.spotify.Client
- name: Install rambox
  become: yes
  yum:
    name: https://github.com/ramboxapp/community-edition/releases/download/0.7.7/rambox-0.7.7-linux-x86_64.rpm
    disable_gpg_check: yes
- name: Install VirtualBox
  become: yes
  yum:
    name: https://download.virtualbox.org/virtualbox/6.1.22/VirtualBox-6.1-6.1.22_144080_el8-1.x86_64.rpm
    disable_gpg_check: yes
- name: Create terminator conf dir
  file:
    path: ~/.config/terminator
    state: directory
    mode: '0755'
- name: Copy terminator config
  copy:
    src: terminator.config
    dest: ~/.config/terminator/config
    mode: '0644'
    force: no
- name: Create ssh dir
  file:
    path: ~/.ssh
    state: directory
    mode: '0755'
- name: Copy user shh config
  copy:
    src: ssh/config
    dest: ~/.ssh/config
    mode: '0600'
- name: Copy bashrc
  copy:
    src: bash/bashrc
    dest: ~/.bashrc
    mode: '0644'
    force: no
- name: Copy bash_profile
  copy:
    src: bash/bash_profile
    dest: ~/.bash_profile
    mode: '0644'
    force: no
- name: Install pip libraries
  pip:
    name: '{{item.name}}'
    executable: '{{item.pip_executable}}'
    extra_args: '--user'
  loop:
# fpasswd
    - name: 'pykeepass'
      pip_executable: 'pip3'
    - name: 'PyInquirer'
      pip_executable: 'pip3'
    - name: 'pyperclip'
      pip_executable: 'pip3'
    - name: 'termcolor'
      pip_executable: 'pip3'
#  Fancy prompt
    - name: 'powerline-shell'
      pip_executable: 'pip3'
# Custom python script
    - name: 'dnspython'
      pip_executable: 'pip3'
